// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD_vSkdDWPw4R1fb5e_8saf-hH91jJLnE',
    appId: '1:590571823887:android:7dbf43d7cfe5a585e4147a',
    messagingSenderId: '590571823887',
    projectId: 'vaqt-b3158',
    storageBucket: 'vaqt-b3158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2CGP5fm0Hh4OVY0532QtB3QyySisfv8M',
    appId: '1:590571823887:ios:0c54ecc9da3e8431e4147a',
    messagingSenderId: '590571823887',
    projectId: 'vaqt-b3158',
    storageBucket: 'vaqt-b3158.firebasestorage.app',
    iosBundleId: 'com.example.vaqt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCDeCBc7jcGGoT0mturmk1wz-yLZ49hJs',
    appId: '1:590571823887:web:333a2ae56af5d7dde4147a',
    messagingSenderId: '590571823887',
    projectId: 'vaqt-b3158',
    authDomain: 'vaqt-b3158.firebaseapp.com',
    storageBucket: 'vaqt-b3158.firebasestorage.app',
    measurementId: 'G-6Z602102K5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2CGP5fm0Hh4OVY0532QtB3QyySisfv8M',
    appId: '1:590571823887:ios:0c54ecc9da3e8431e4147a',
    messagingSenderId: '590571823887',
    projectId: 'vaqt-b3158',
    storageBucket: 'vaqt-b3158.firebasestorage.app',
    iosBundleId: 'com.example.vaqt',
  );

}